#:schema https://github.com/YunoHost/apps/raw/master/schemas/config_panel.v1.schema.json

version = "1.0"

[main]
name = "Configuration"

    [main.server_side]
    name.en = "Server-side features'"
    name.fr = "Fonctionnalités côté serveur"
    optional = false

        [main.server_side.htmltopdf_enabled]
        ask.en = "Enable HTML to PDF conversion service"
        ask.fr = "Activer le service de conversion HTML vers PDF"
        type = "boolean"
        help.en = "When enabled, it offers an API endpoint to be used in the 'HTML to PDF' tool page. Cf. details in the admin documentation."
        help.fr = "Si activé, un ouvre un point de terminaison API à utiliser dans la page de l'outil 'HTML to PDF'. Cf. détails dans la documentation admin."
        bind = "null"

        [main.server_side.basic_auth_username]
        ask.en = "Username for API endpoints basic authentication"
        ask.fr = "Nom d'utilisateur pour l'authentification basique aux points API"
        type = "string"
        help.en = "More details on where to use this in the admin documentation."
        help.fr = "Plus de détails sur où utiliser ceci dans la documentation admin."
        #pattern.regexp = "[^\\']+"
        #pattern.error = "Can neither be empty nor contain single quote."
        bind = "null"
        visible = "htmltopdf_enabled"

        [main.server_side.basic_auth_password]
        ask.en = "Password for API endpoints basic authentication"
        ask.fr = "Mot de passe pour l'authentification basique aux points API"
        type = "password"
        help.en = "More details on where to use this in the admin documentation."
        help.fr = "Plus de détails sur où utiliser ceci dans la documentation admin."
        #pattern.regexp = "[^\\']+"
        #pattern.error = "Can neither be empty nor contain single quote."
        bind = "null"
        visible = "htmltopdf_enabled"
