packaging_format = 2

id = "it-tools"
name = "IT Tools"
description.en = "Collection of handy online tools for developers"
description.fr = "Collection d'outils pratiques en ligne pour les développeurs"

version = "2026.08.01~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "GPL-3.0-only"
demo = "https://sharevb-it-tools.vercel.app"
code = "https://github.com/sharevb/it-tools"
fund = "https://www.buymeacoffee.com/sharevb"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "20M"
ram.runtime = "20M"


[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/it-tools"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/sharevb/it-tools/archive/db3a344568155762599750927c37dea4f1f1833c.tar.gz"
        sha256 = "94cdcd0ac898f0513296c2ffd86bac2213c9976ce4d4c25346392374bc08a08d"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/YunoHost-Apps/it-tools_ynh/releases/download/v2026.07.26-be4d2258/it-tools_v2026.07.26-be4d2258_ynh.zip"
        sha256 = "8732a49ac6f2acde38d30c6a2e976a21d7fac95c8f9e9b30d34a7c14a1966b6e"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3, make, g++"
