packaging_format = 2

id = "it-tools"
name = "IT Tools"
description.en = "Collection of handy online tools for developers"
description.fr = "Collection d'outils pratiques en ligne pour les développeurs"

version = "2026.08.30~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "GPL-3.0-only"
demo = "https://sharevb-it-tools.vercel.app"
code = "https://github.com/sharevb/it-tools"
fund = "https://www.buymeacoffee.com/sharevb"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "20M"
ram.runtime = "20M"


[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/it-tools"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/sharevb/it-tools/archive/5bf94bc56781af63915b5194177d21becc92ff05.tar.gz"
        sha256 = "26494657fea5e2660a68f23c5f032f0b4b6641324f7a7f398e367b98f2da2e15"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/YunoHost-Apps/it-tools_ynh/releases/download/v2026.08.30-5bf94bc5/it-tools_v2026.08.30-5bf94bc5_ynh.zip"
        sha256 = "6e1185d1fcdef6ca4d1363f1e9b040505009e334d763bf50db7c1e2eaaddd4fc"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3, make, g++"
