packaging_format = 2

id = "it-tools"
name = "IT Tools"
description.en = "Collection of handy online tools for developers"
description.fr = "Collection d'outils pratiques en ligne pour les développeurs"

version = "2026.08.16~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "GPL-3.0-only"
demo = "https://sharevb-it-tools.vercel.app"
code = "https://github.com/sharevb/it-tools"
fund = "https://www.buymeacoffee.com/sharevb"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "20M"
ram.runtime = "20M"


[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/it-tools"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/sharevb/it-tools/archive/fbc7d47fbd543633d45c4858e62b7c694945ca78.tar.gz"
        sha256 = "c7e09e561c4c4374d0730d1b68973329bc65a967220db9fe591ebf925754f5de"
        prefetch = false
        autoupdate.strategy = "latest_github_commit"
        
        [resources.sources.ynh_build]
        url = "https://github.com/YunoHost-Apps/it-tools_ynh/releases/download/v2026.08.07-c82794af/it-tools_v2026.08.07-c82794af_ynh.zip"
        sha256 = "36472594327f07229741e7d8407331a0930c4dbf7da804535c248ee0dc3555a7"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3, make, g++"
