#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/;

  index index.html;
  try_files $uri $uri/ __PATH__/index.html;

  # Set correct MJS mime type as it is an unknown filetype to Nginx which
  #   loads related files as 'application/octet-stream' type by default
  include mime.types;
  types {
      application/javascript js mjs;
  }

  # Security headers
  more_set_headers "X-Frame-Options: SAMEORIGIN always";
  more_set_headers "X-Content-Type-Options: nosniff always";
  more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
  more_set_headers "Cross-Origin-Opener-Policy: same-origin always";
  more_set_headers "X-Permitted-Cross-Domain-Policies: none";
  more_set_headers "Cross-Origin-Embedder-Policy: require-corp always";
  more_set_headers "Cross-Origin-Resource-Policy: cross-origin always";
}

location ^~ __PATH__/pdf/url {
   proxy_pass http://127.0.0.1:__PORT__/;
   include    proxy_params_no_auth;
}
