#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# CHANGE HARDCODED URLS IN APP FILES
#=================================================

# Prepare var for string replacement (empty if $path is root or $path if subdir is defined)
old_path_2=""
if [[ $old_path != '/' ]]; then old_path_2=$old_path; fi
new_path_2=""
if [[ $new_path != '/' ]]; then new_path_2=$new_path; fi

# Change strings
ynh_replace --match="https://$old_domain$old_path" --replace="https://$new_domain$new_path" --file="$install_dir/index.html"
ynh_replace --match="<base href=\"$old_path_2/\">" --replace="<base href=\"$new_path_2/\">" --file="$install_dir/index.html"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
