#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEYS
#=================================================
get__htmltopdf_enabled() {
    htmltopdf_enabled=$(ynh_app_setting_get --key=htmltopdf_enabled)
    echo "${htmltopdf_enabled}"
}

get__basic_auth_enabled() {
    basic_auth_enabled=$(ynh_app_setting_get --key=basic_auth_enabled)
    echo "${basic_auth_enabled}"
}

get__basic_auth_username() {
    local auth_string=$(itt_helper_get_basic_auth_string)
    local username="${auth_string%%:*}" #extract username before colon sign
    echo "${username}"
}

get__basic_auth_password() {
    echo "" #do not show password for security purpose
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__htmltopdf_enabled() {
    ynh_app_setting_set --key=htmltopdf_enabled --value="$htmltopdf_enabled"
    if [ $htmltopdf_enabled -eq 1 ]; then
        ynh_permission_update --permission="puppeteer-htmltopdf" --add="visitors"
        ynh_systemctl --service=$app-puppeteer --action=start #--wait_until="Started"
    elif [ $htmltopdf_enabled -eq 0 ]; then
        ynh_permission_update --permission="puppeteer-htmltopdf" --remove="visitors"
        ynh_systemctl --service=$app-puppeteer --action=stop #--wait_until="Consumed"
    fi
}

set__basic_auth_enabled() {
    ynh_app_setting_set --key=basic_auth_enabled --value="$basic_auth_enabled"
    if [ $basic_auth_enabled -eq 1 ]; then
        local is_basic_auth_var=$(cat "$install_dir/puppeteer-htmltopdf/.env" | grep BASIC_AUTH)
        if [[ -z "$is_basic_auth_var" ]]; then
            echo "BASIC_AUTH=" >> "$install_dir/puppeteer-htmltopdf/.env"
        fi
    elif [ $basic_auth_enabled -eq 0 ]; then
        sed '/^\s*BASIC_AUTH=/d' "$install_dir/puppeteer-htmltopdf/.env"
    fi
    ynh_systemctl --service=$app-puppeteer --action=restart #--wait_until="Started"
}

set__basic_auth_username() {
    local auth_string=$(itt_helper_get_basic_auth_string)
    local password="${auth_string#*:}" #extract password after colon sign
    ynh_replace --match="^BASIC_AUTH=.*$" --replace="BASIC_AUTH='$basic_auth_username\:$password'" --file="$install_dir/puppeteer-htmltopdf/.env"
    ynh_app_setting_set --key=basic_auth_username --value="$basic_auth_username"
    ynh_systemctl --service=$app-puppeteer --action=restart #--wait_until="Started"
}


set__basic_auth_password() {
    local auth_string=$(itt_helper_get_basic_auth_string)
    local username="${auth_string%%:*}" #extract username before colon sign
    ynh_replace --match="^BASIC_AUTH=.*$" --replace="BASIC_AUTH='$username\:$basic_auth_password'" --file="$install_dir/puppeteer-htmltopdf/.env"
    ynh_systemctl --service=$app-puppeteer --action=restart #--wait_until="Started"
}

#=================================================
ynh_app_config_run "$1"
