#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

#Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace URL placeholder with $path only in specific cases
index_js_path="$(sed --regexp-extended --silent 's@\s*<script type="module" crossorigin src=".*/(assets/index-[^.]*\.js)\"></script>@\1@p' $install_dir/index.html)" #e.g. assets/index-86994da2.js
sed --regexp-extended --in-place "s@([a-zA-Z0-9^=]*)=\"modulepreload\",([a-zA-Z0-9^=]*)=function\(([a-zA-Z0-9^=]*)\)\{return\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__/\"@\1=\"modulepreload\",\2=function\(\3\)\{return\"$newpath/\"@g" $install_dir/$index_js_path
sed --regexp-extended --in-place "s@loadEnv\(\{BASE_URL:\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__@loadEnv({BASE_URL:\"$path/@g" $install_dir/$index_js_path

# Various specific path fixes
sed --in-place 's/age-wasm\/wasm_exec\.js/\/age-wasm\/wasm_exec.js/g' $install_dir/assets/age-crypto-*
ynh_replace --match="tools-filter.json" --replace="/tools-filter.json" --file="$install_dir/$index_js_path"
ynh_replace --match="tools-settings.json" --replace="/tools-settings.json" --file="$install_dir/$index_js_path"
ynh_replace --match="external-tools.json" --replace="/external-tools.json" --file="$install_dir/$index_js_path"
ynh_replace --match="home.custom.md" --replace="/home.custom.md" --file="$install_dir/$index_js_path"
ynh_replace --match="https://sharevb-it-tools.vercel.app" --replace="https://$domain$path" --file="$install_dir/index.html"

# Replace URL placeholder with absolute URL for all files of the app folder
match_regex="/?__YNH_DOMAIN____YNH_SUBDIR_PATH__"
grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@https://$domain$newpath@g"

#=================================================
# INSTALL DEPENDENCIES 
#=================================================
ynh_script_progression "Install dependencies..."

# Puppeteer HTML to PDF server
ynh_setup_source --dest_dir="$install_dir/puppeteer-htmltopdf" --source_id="puppeteer-htmltopdf"
pushd "$install_dir/puppeteer-htmltopdf"
    ynh_hide_warnings ynh_exec_as_app npm install 
popd
ynh_config_add --template=".env" --destination="$install_dir/puppeteer-htmltopdf/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app-puppeteer" --description="IT-Tools Puppeteer server for HTML to PDF conversion" --log="/var/log/$app/$app-puppeteer.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
