#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-puppeteer.service"
systemctl enable "$app-puppeteer.service" --quiet

yunohost service add "$app" --description="IT-Tools Puppeteer server for HTML to PDF conversion" --log="/var/log/$app/$app-puppeteer.log"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
