#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

upstream_source_url=$(ynh_read_manifest "resources.sources.main.url")
source_filename=$(basename $upstream_source_url)
#this variable will also populate the template tag __INDEX_PAGE__ in nginx.conf
index_page=$(basename -s .zip $upstream_source_url).html

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."
	
ynh_setup_source --dest_dir="$install_dir" --full_replace
#replace link to local source file with link to upstream source file
ynh_replace --match="$source_filename" --replace="$upstream_source_url" --file="$install_dir/$index_page"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
